In [2]:
import pandas as pd

In [3]:
# death_metal.csv
url = 'https://drive.google.com/file/d/11HsCgxJL_PtJ8xxdT5VZbw6e0y0-VKag/view?usp=sharing' 
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
bands = pd.read_csv(path)

In [3]:
bands.head()

,name,country,status,formed_in,genre,theme,active
0,**Act of Destruction?>,united states,ac,2005.0,Melodic Death/Thrash Metal,Death| Love| Life| Evil| Darker Tones,2005-present
1,**Nirvana 2002?>,sweden,su,1988.0,Death Metal,Metaphysical Philosophy| Parapsychology,1988-1992
2,**Olemus?>,austria,ac,1993.0,Death/Black/Gothic Metal,Sadness| Life| Death,1993-present
3,**Misanthrope?>,mexico,oh,2010.0,Death Metal,Death| Destruction| War| Decadence,2010-present
4,**Detonator?>,russia,su,1991.0,Technical Death/Thrash Metal,Loneliness philosophy| state of mind of the pe...,1991-2002

In [ ]:
bands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       26 non-null     object
 1   country    26 non-null     object
 2   status     26 non-null     object
 3   formed_in  26 non-null     float64
 4   genre      26 non-null     object
 5   theme      26 non-null     object
 6   active     26 non-null     object
dtypes: float64(1), object(6)
memory usage: 1.5+ KB

### **Exercise 1:** 
Cleaning the 'name' column

The names of the bands are messy. They have some extra characters like '\*\*' at the begining and '?>' at the end. Remove them using any or all of these methods:  
- [pandas.Series.str.replace](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html)
- [pandas.Series.str.lstrip](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.lstrip.html)
- [pandas.Series.str.rstrip](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.rstrip.html)
- [pandas.Series.str.strip](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html)

In [4]:
bands['name'].head(5)

0    **Act of Destruction?>
1          **Nirvana 2002?>
2                **Olemus?>
3           **Misanthrope?>
4             **Detonator?>
Name: name, dtype: object

In [5]:
# your code here
bands['name'].str.replace('[^a-zA-Z]','')

<ipython-input-5-4887c0f15ae5>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  bands['name'].str.replace('[^a-zA-Z]','')

0     ActofDestruction
1              Nirvana
2               Olemus
3          Misanthrope
4            Detonator
5           BloodAgent
6           Traumagain
7           Anaktorian
8               Revolt
9           Coldworker
10        TotalCarnage
11        TheAwakening
12         FeuGregeois
13             Nemesis
14               Grind
15         Gloomlurker
16                Dark
17              Midian
18           Desecrate
19              Mortum
20        AColdReality
21        CasttheStone
22         Persecution
23         Stigmatizer
24            Ravenage
25            Riverden
Name: name, dtype: object

### **Exercise 2:** 
Cleaning the country column

The country column has all countries written with small capital letter. Change them so they have all capital letters.  
Best method for this is: [pandas.Series.str.title](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.title.html)

In [6]:
bands['country'].head(5)

0    united states
1           sweden
2          austria
3           mexico
4           russia
Name: country, dtype: object

In [7]:
# your code here
bands['country'].str.upper()

0      UNITED STATES
1             SWEDEN
2            AUSTRIA
3             MEXICO
4             RUSSIA
5            GERMANY
6              ITALY
7            FINLAND
8              ITALY
9             SWEDEN
10       SWITZERLAND
11           GERMANY
12            FRANCE
13          COLOMBIA
14    CZECH REPUBLIC
15    UNITED KINGDOM
16           GERMANY
17      KOREA| SOUTH
18          MALAYSIA
19            SWEDEN
20     UNITED STATES
21     UNITED STATES
22         AUSTRALIA
23           GERMANY
24    UNITED KINGDOM
25     UNITED STATES
Name: country, dtype: object

### **Exercise 3:**
Cleaning the status column

The status column has some abbreviations instead of the real status.  
Change them in accordance with this:  
* ac = Active  
* su = Split-up  
* cn = Changed name  
* oh = On hold  
* un = Unknown

You can use  
pandas.Series.str.replace -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html  
or you can create a dictionary and remap values according to it with  
pandas.Series.replace -> https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html

In [4]:
bands['status'].head(5)

0    ac
1    su
2    ac
3    oh
4    su
Name: status, dtype: object

In [8]:
# your code here
bands.loc[bands['status']=='ac','status'] = 'Active'
bands.loc[bands['status']=='su','status'] = 'Split-up'
bands.loc[bands['status']=='cn','status'] = 'Changed name'
bands.loc[bands['status']=='oh','status'] = 'On hold'
bands.loc[bands['status']=='un','status'] = 'Unknown'
bands.head(5)

,name,country,status,formed_in,genre,theme,active
0,**Act of Destruction?>,united states,Active,2005.0,Melodic Death/Thrash Metal,Death| Love| Life| Evil| Darker Tones,2005-present
1,**Nirvana 2002?>,sweden,Split-up,1988.0,Death Metal,Metaphysical Philosophy| Parapsychology,1988-1992
2,**Olemus?>,austria,Active,1993.0,Death/Black/Gothic Metal,Sadness| Life| Death,1993-present
3,**Misanthrope?>,mexico,On hold,2010.0,Death Metal,Death| Destruction| War| Decadence,2010-present
4,**Detonator?>,russia,Split-up,1991.0,Technical Death/Thrash Metal,Loneliness philosophy| state of mind of the pe...,1991-2002

### **Exercise 4:**
Cleaning the genre column

The column genre has genres in a single string separated by character /  
1. First, transform the string to list of strings  
(e.g. 'Avant-garde Black/Death Metal'    to     \[Avant-garde Black, Death Metal\]  
1. Then, create a new column 'number_of_genres' where you will store the number of genres in each list.  

Methods you can use are:  
pandas.Series.str.split -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html  
pandas.Series.str.len -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.len.html

In [ ]:
bands['genre'].head(5)

0      Melodic Death/Thrash Metal
1                     Death Metal
2        Death/Black/Gothic Metal
3                     Death Metal
4    Technical Death/Thrash Metal
Name: genre, dtype: object

In [17]:
# your code here
bands['number_of_genres'] = bands['genre'].str.split('/').str.len() # count
# print(number_of_genres)
bands.head(5)

,name,country,status,formed_in,genre,theme,active,number_of_genres
0,**Act of Destruction?>,united states,Active,2005.0,Melodic Death/Thrash Metal,Death| Love| Life| Evil| Darker Tones,2005-present,2
1,**Nirvana 2002?>,sweden,Split-up,1988.0,Death Metal,Metaphysical Philosophy| Parapsychology,1988-1992,1
2,**Olemus?>,austria,Active,1993.0,Death/Black/Gothic Metal,Sadness| Life| Death,1993-present,3
3,**Misanthrope?>,mexico,On hold,2010.0,Death Metal,Death| Destruction| War| Decadence,2010-present,1
4,**Detonator?>,russia,Split-up,1991.0,Technical Death/Thrash Metal,Loneliness philosophy| state of mind of the pe...,1991-2002,2

### **Exercise 5:** 
Cleaning the active column

The column `active` contains information about the years when a band was active or '?' if the status or year is unknown.  

Create two new columns 
- `active_from`: when the band formed
- `active_to`: when the band broke up

and fill them with the information contained in the column `active`.  

Method you can use is: pandas.Series.str.extract -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.extract.html#

In [ ]:
bands['active'].head(5)

0    2005-present
1       1988-1992
2    1993-present
3    2010-present
4       1991-2002
Name: active, dtype: object

In [37]:
# your code here
# a = bands.active.str.extract(r'(\d{4}$)') #-> active_from
# get bands.active.str.extract('$x') -> active_to
bands['active_from'] = bands.active.str.split('-').str[0]
bands['active_to'] = bands.active.str.split('-').str[1]

bands.head(5)

,name,country,status,formed_in,genre,theme,active,number_of_genres,active_from,active_to
0,**Act of Destruction?>,united states,Active,2005.0,Melodic Death/Thrash Metal,Death| Love| Life| Evil| Darker Tones,2005-present,2,2005,present
1,**Nirvana 2002?>,sweden,Split-up,1988.0,Death Metal,Metaphysical Philosophy| Parapsychology,1988-1992,1,1988,1992
2,**Olemus?>,austria,Active,1993.0,Death/Black/Gothic Metal,Sadness| Life| Death,1993-present,3,1993,present
3,**Misanthrope?>,mexico,On hold,2010.0,Death Metal,Death| Destruction| War| Decadence,2010-present,1,2010,present
4,**Detonator?>,russia,Split-up,1991.0,Technical Death/Thrash Metal,Loneliness philosophy| state of mind of the pe...,1991-2002,2,1991,2002

### **Exercise 6** 
Counting the themes

Count how many times do the words Love, Life, Death repeat in a themes column.  
Method you can use is:  
pandas.Series.str.count -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.count.html

In [ ]:
bands['theme'].head(5)

0                Death| Love| Life| Evil| Darker Tones
1              Metaphysical Philosophy| Parapsychology
2                                 Sadness| Life| Death
3                   Death| Destruction| War| Decadence
4    Loneliness philosophy| state of mind of the pe...
Name: theme, dtype: object

In [29]:
# your code here
bands['theme'].str.extractall(r'(Love|Life|Death)+').count()
# bands['theme']

0    19
dtype: int64

## Final result

In [38]:
bands

,name,country,status,formed_in,genre,theme,active,number_of_genres,active_from,active_to
0,**Act of Destruction?>,united states,Active,2005.0,Melodic Death/Thrash Metal,Death| Love| Life| Evil| Darker Tones,2005-present,2,2005,present
1,**Nirvana 2002?>,sweden,Split-up,1988.0,Death Metal,Metaphysical Philosophy| Parapsychology,1988-1992,1,1988,1992
2,**Olemus?>,austria,Active,1993.0,Death/Black/Gothic Metal,Sadness| Life| Death,1993-present,3,1993,present
3,**Misanthrope?>,mexico,On hold,2010.0,Death Metal,Death| Destruction| War| Decadence,2010-present,1,2010,present
4,**Detonator?>,russia,Split-up,1991.0,Technical Death/Thrash Metal,Loneliness philosophy| state of mind of the pe...,1991-2002,2,1991,2002
5,**Blood Agent?>,germany,Active,2013.0,Death/Thrash Metal,War| Death| Apocalypse,2013-present,2,2013,present
6,**Traumagain?>,italy,Active,2001.0,Brutal Death Metal,Nihilism| Death,2001-present,1,2001,present
7,**Anaktorian?>,finland,Split-up,2001.0,Melodic Death Metal,Death| emotions| pain,2001-2007,1,2001,2007
8,**Revolt?>,italy,Changed name,2001.0,Death/Thrash Metal,Society| Hate,2001-2006,2,2001,2006
9,**Coldworker?>,sweden,Split-up,2006.0,Death Metal,Death,2006-2013,1,2006,2013
10,**Total Carnage?>,switzerland,Split-up,2010.0,Death Metal/Crust,Post-Apocalypse| Nuclear Warfare| WW3,2010-2011,2,2010,2011
11,**The Awakening?>,germany,Split-up,1998.0,Death Metal,Human existence| Apocalyptic visions| Nightmares,1998-2008,1,1998,2008
12,**Feu Gregeois?>,france,Changed name,2005.0,Black/Death Metal,Medieval themes,2005-?,2,2005,?
13,**Nemesis?>,colombia,Split-up,1986.0,Death/Thrash Metal,Destiny| Death,1986-?,2,1986,?
14,**Grind 6|4?>,czech republic,Active,1997.0,Brutal Death Metal/Grindcore,Working accidents,1997-present,2,1997,present
15,**Gloomlurker?>,united kingdom,Split-up,2012.0,Melodic Death/Doom Metal,Death| Curses| Strength| Power,2012-2013,2,2012,2013
16,**Dark?>,germany,Split-up,1991.0,Death/Thrash Metal (early)| Dark/Gothic Metal ...,Darkness| Depression| Nature| Love,1991-?,3,1991,?
17,**Midian?>,korea| south,Active,2009.0,Melodic Death Metal,Despair| Salvation| Duality,2009-present,1,2009,present
18,**Desecrate?>,malaysia,Active,2014.0,Death/Thrash/Progressive Metal,Anti Nuclear Power,2014-present,3,2014,present
19,**Mortum?>,sweden,Split-up,1997.0,Melodic Death/Black Metal,Love| Death| Fantasy,1997-1998,2,1997,1998
20,**A Cold Reality?>,united states,Split-up,1999.0,Thrash/Death Metal,Corruption| Society| Relationships,1999-2008,2,1999,2008
21,**Cast the Stone?>,united states,Unknown,2002.0,Death Metal,Death| Corruption,2002-?,1,2002,?
22,**Persecution?>,australia,Split-up,1989.0,Death Metal,Political| Social,1989-?,1,1989,?
23,**Stigmatizer?>,germany,Split-up,2004.0,Death Metal,Life| Death| Society,2004-2007,1,2004,2007
24,**Ravenage?>,united kingdom,Active,2007.0,Folk/Melodic Death Metal,Battles| Mythology,2007-present,2,2007,present
25,**Riverden?>,united states,On hold,2004.0,Thrash/Death Metal,Life| Experiences| Nature| History,2004-2012,2,2004,2012